### ISSUE TITLE
Failed Scans - Sleep Status Icon

### ISSUE THREAD

**Issue by ofir-mev** [ssjshields/archetype-counter#24]
[DEBUG_OCR_OUTPUT.txt](https://github.com/ssjshields/archetype-counter/files/12557602/DEBUG_OCR_OUTPUT.txt)
![ArchetypeScreenshot](https://github.com/ssjshields/archetype-counter/assets/57320827/7169fd12-cccd-4992-a59e-8ebc8b616ae0)
![ArchetypeScreenshotEncounter](https://github.com/ssjshields/archetype-counter/assets/57320827/a539191c-4004-447b-ba6c-cbbb9e92e9bc)
![ArchetypeScreenshotMagick](https://github.com/ssjshields/archetype-counter/assets/57320827/05dbf6d1-58aa-4aa2-a8e1-951be5db38d4)

happen to me two times already :(

**Comment by ssjshields** [comment]
@ofir-mev Sleep status icon is causing scan to be processed as "uFearow".

Open the **CounterConfig_PokemonNameFix** text file and add to a new line: `uFearow; Fearow` should resolve this issue.
The problem is if it is not consistently processing as "uFearow", it will still happen. 

Please make sure you're on the latest Counter build (main) and standby for more information regarding this issue.

This does not occur in Archetype theme as our sleep icon doesn't get picked up.

In future updates, @AnonymousPoke is changing the Counter from Windows OCR to tesseract, which should help with these niche cases.

**Comment by AnonymousPoke** [comment]
@ofir-mev, downloading the latest main build should now resolve this issue.
